### ISSUE TITLE
HTML is not parsed in the short description

### ISSUE THREAD

**Issue by agatemosu** [lotusprey/otraku#108]
Example: https://anilist.co/anime/19111

I think that the correct word is "parsed" but if it's not, I mean that HTML tags can be viewed

**Comment by nstrelow** [comment]
The app already parses this correctly when clicking on the description to make it pop out.

Probably reusing the same code for this part might be not to difficult.

@lotusprey Would this be something I could look into?

**Comment by lotusprey** [comment]
Media descriptions (unfortunately) use a bit of markdown, so I started requesting them as HTML from the API. When the description gets expanded, I use the `flutter_widget_from_html_core` package to present it correctly. I don't resort to that in the description preview, because I need to only show a segment of the description and using the package functionality there didn't seem like an optimal solution. I will probably end up using it, we will see.

**Comment by lotusprey** [comment]
Fixed in #113. I will close the issue, when the next update is released.

**Comment by lotusprey** [comment]
I closed is accidentally earlier, but now this is completed in version 1.2.7, for which there's currently a pre-release, but the official release will be out soon.
