### ISSUE TITLE
Statistics pie charts on iOS only one color and missing status names

### ISSUE THREAD

**Issue by chriskgames** [lotusprey/otraku#119]
Shown below should be a screenshot. Where it says Format on the right repeatedly it should be TV or OVA, and planned, watched, watching, respectively 

![IMG_2660](https://github.com/lotusprey/otraku/assets/104114275/22f3ae57-95ab-45df-b4b8-7b91eb82d2e1)

**Comment by lotusprey** [comment]
The bug with the labels is fixed locally. It will be fine in the next release.
As far as the color goes, currently, the sections are only distinguished by the dividers. Choosing appropriate colors is hard, because of the app theming, but maybe I will come up with a better design in the future.
I will close this, when I push the next release.

**Comment by lotusprey** [comment]
Closing this as resolved in version 1.2.7, for which there's currently a pre-release, but the official release will be out soon.
