### ISSUE TITLE
Support 90 Hz framerate

### ISSUE THREAD

**Issue by d4f5409d** [lotusprey/otraku#56]

**Comment by lotusprey** [comment]
Flutter (the framework I'm using to build the app) supports high frame rates and I am finally able to confirm with a device that everything is fine (at 120Hz even). I will close this. If anybody has a problem with that, they should make a more detailed issue with OS, device model, e.t.c.

**Comment by d4f5409d** [comment]
Flutter sucks. I've had this problem with Flutter apps on my device back then as well. It seems to work with 120 Hz but not with 90 Hz. A patch is needed to fix it. There are hotfixes for this out there for sure, because a developer from another app found it and it works, however, it is needed to be in there always, everytime to not experience the error. (OnePlus8)

**Comment by lotusprey** [comment]
Interesting - searching online, there's indeed a problem with flutter on OnePlus devices. Unfortunately, I don't think I can do much now, as this issue is specific to that manufacturer. I have a high refresh rate device, but it's a Samsung one, and I have no way of debugging device-specific problems.
